# Generated by Django 2.1.5 on 2019-02-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Equipo', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('Codigo_liga', models.AutoField(primary_key=True, serialize=False)),
                ('Nacion', models.CharField(max_length=25)),
                ('Liga', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeTeam', models.CharField(max_length=50)),
                ('AwayTeam', models.CharField(max_length=50)),
                ('date_match', models.DateField()),
                ('GoalsHome', models.PositiveIntegerField()),
                ('GoalsAway', models.PositiveIntegerField()),
                ('Result', models.CharField(max_length=1)),
                ('Cod_Liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soccer.Ligas')),
            ],
        ),
    ]
