# Generated by Django 2.1.5 on 2019-02-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreliga', models.CharField(db_index=True, max_length=40)),
                ('Anho', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallesPartidoGoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GolesHalfHome', models.PositiveSmallIntegerField(default=0)),
                ('GolesHalfAway', models.PositiveSmallIntegerField(default=0)),
                ('ResultadoHalf', models.CharField(max_length=1)),
                ('GolesFullHome', models.PositiveSmallIntegerField(default=0)),
                ('GolesFullAway', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreteam', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(default=0)),
                ('equi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='futbol.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='futbol.competicion')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ganador', models.CharField(max_length=1)),
                ('Fecha', models.DateField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away', to='futbol.equipo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home', to='futbol.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='futbol.competicion')),
            ],
        ),
        migrations.AddField(
            model_name='detallespartidogoles',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='futbol.Partido'),
        ),
    ]
